org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.jvm.target.validation.mode=warning
#org.gradle.daemon=false
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
#org.gradle.caching=false
#org.gradle.parallel=false
#org.gradle.workers.max=1
#org.gradle.configureondemand=false
org.gradle.java.home=C\:/Program Files/Java/jdk-17
